'use strict';
const TOKEN=document.querySelector('meta[name="mv-token"]').content;
const $=id=>document.getElementById(id);
let migrationPreview=null;
let state={view:'home',filter:'all',q:'',sort:'recent',page:1,limit:54,total:0,config:{},movie:null,job:null,groups:[],group:'',subtitleSources:['Unknown','Netflix','OSN','Amazon Prime Video','Disney+','Manual','Other'],modalBackMovieId:null};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const size=b=>{if(b==null)return '—';let n=Number(b),u=['B','KB','GB','TB'];if(n<1024)return `${n} B`;let unit='MB';n/=1024;if(n>=1024){n/=1024;unit='MB';}else{unit='KB';}if(n>=1024){n/=1024;unit='GB';}if(n>=1024){n/=1024;unit='TB';}return `${n.toFixed(n>=100?0:n>=10?1:2)} ${unit}`};
const bit=b=>b?`${Number(b/1000).toLocaleString(undefined,{maximumFractionDigits:0})} kbps`:'Not available';
const artwork=(id,ver='')=>`/artwork/${id}?k=${encodeURIComponent(TOKEN)}&v=${encodeURIComponent(ver||'1')}`;
async function api(path,method='GET',body){const options={method,headers:{'X-MovieVault-Token':TOKEN}};if(body!==undefined){if(body instanceof Blob){options.body=body;options.headers['Content-Type']=body.type||'application/octet-stream';}else{options.body=JSON.stringify(body);options.headers['Content-Type']='application/json';}}
let r;try{r=await fetch(path,options)}catch(e){throw Error('Cannot reach the local MovieVault service. '+e.message)};let d=await r.json();if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d;}
function toast(msg,error=false){const el=$('toast');el.textContent=msg;el.classList.toggle('error',error);el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),4900)}
async function safe(task){try{return await task()}catch(e){toast(e.message,true);console.error(e)}}
function openModal(html,width='medium'){$('modalContent').className=`dialog ${width}`;$('modalContent').innerHTML='<button class="dialog-close" id="closeModal" aria-label="Close">×</button>'+html;$('modalOverlay').classList.remove('hidden');$('closeModal').onclick=closeModal;}
function closeModal(){const back=state.modalBackMovieId;state.modalBackMovieId=null;if(back){safe(()=>showMovie(back));return;}$('modalOverlay').classList.add('hidden');$('modalContent').innerHTML='';}
$('modalOverlay').onclick=e=>{if(e.target.id==='modalOverlay')closeModal()};
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if(e.ctrlKey&&e.key.toLowerCase()==='k'){e.preventDefault();if(state.view==='settings')setView('home');$('search').focus();}});
function updateSidebar(data){const st=data.stats;state.config=data.settings||{};$('total').textContent=Number(st.total).toLocaleString();$('available').textContent=Number(st.available).toLocaleString();$('missing').textContent=Number(st.missing).toLocaleString();$('offline').textContent=Number(st.offline).toLocaleString();$('store').textContent=size(st.disk_bytes);$('groups').textContent=`${st.groups} groups`;$('meterfill').style.width=Math.min(100,st.catalog_bytes?100*st.disk_bytes/st.catalog_bytes:0)+'%';$('footerStats').textContent=`${st.total} cataloged movies · ${size(st.disk_bytes)} currently online`;$('ffstatus').textContent=st.ffprobe_found?'ffprobe connected — technical scan ready':'ffprobe not found — basic file scan only';$('ffstatus').className=st.ffprobe_found?'green':'rose';$('dataDir').textContent='Data directory: '+data.data_dir;
$('rootList').innerHTML=(data.roots||[]).map(r=>`<div class="root"><div class="roothead"><span class="${r.last_status==='online'?'good':'bad'}">●</span><b title="${esc(r.path)}">${esc(r.path.split(/[\\/]/).filter(Boolean).pop()||r.path)}</b></div><small title="${esc(r.path)}">${esc(r.last_status||'Unscanned')} · Hover for location</small></div>`).join('')||'<p class="caption">No folders added yet.</p>';
$('rootSettings').innerHTML=(data.roots||[]).map(r=>`<div class="switchrow"><div><b>${esc(r.path)}</b><small>Status: ${esc(r.last_status||'unscanned')} · Last scan: ${esc(r.last_scan||'Never')}</small></div><button class="secondary" data-remove-root="${r.id}">Remove Watch</button></div>`).join('')||'<div class="help">Add a folder to start building your archive.</div>';
for(const el of document.querySelectorAll('[data-setting]'))el.checked=state.config[el.dataset.setting]==='1';$('posterProvider').value=state.config.poster_provider||'commons';$('tmdbStatus').textContent=data.tmdb?.connected?'TMDB connected (token saved locally; secret hidden).':'TMDB not connected yet. Wikimedia Commons is still available.';$('disconnectTmdb').disabled=!data.tmdb?.connected;document.documentElement.dataset.theme=state.config.theme||'dark';$('themeChoice').value=state.config.theme||'dark';$('defaultSubLang').value=state.config.default_external_subtitle_lang||'Arabic';$('imdbState').textContent=st.imdb_imported_at?'IMDb dataset last imported: '+st.imdb_imported_at:'No IMDb dataset imported yet. Filename metadata still works.';$('migrationBanner').classList.toggle('hidden',!!(st.total||st.imdb_imported_at));$('geminiState').textContent=data.gemini?.connected?'Gemini connected securely. Key hidden.':'Gemini is optional and disconnected.';$('geminiModel').value=data.gemini?.model||'';$('disconnectGemini').disabled=!data.gemini?.connected;$('imdbRatingsState').textContent=st.imdb_ratings_at?'IMDb ratings last updated: '+st.imdb_ratings_at:'IMDb ratings not imported yet.';
if(data.active_job&&data.active_job.state==='running')watchJob(data.active_job.id);}
async function refreshBase(){let d=await api('/api/bootstrap');updateSidebar(d);return d;}
function queryOptions(){const status=state.view==='archived'?(state.filter==='offline'?'offline':'missing'):(state.filter==='missing'||state.filter==='offline'?state.filter:'');let quality=['4K','1080p','720p','arabic_subs','no_subs','poster_missing'].includes(state.filter)?state.filter:'';
const args=new URLSearchParams({q:state.group?'':state.q,status,quality,sort:state.sort,page:state.page,limit:state.limit});if(state.group)args.set('release_group',state.group);
for(const [field,id] of Object.entries({genre:'fGenre',actor:'fActor',subtitle_language:'fSubtitleLanguage',subtitle_source:'fSubtitleSource',translator:'fTranslator',year_from:'fYearFrom',year_to:'fYearTo',favorite:'fFavorite'})){const value=$(id).value.trim();if(value)args.set(field,value);}
return args.toString();}
async function refreshMovies(){const result=await api('/api/movies?'+queryOptions());state.total=result.total;$('countLabel').textContent=result.total.toLocaleString()+' movies';$('pageLabel').textContent=`Page ${state.page} / ${Math.max(1,Math.ceil(result.total/state.limit))}`;$('prevBtn').disabled=state.page<=1;$('nextBtn').disabled=state.page*state.limit>=result.total;
$('movieGrid').innerHTML=result.items.length?result.items.map(movieCard).join(''):'<div class="empty-state"><strong>No movies here yet</strong><p>Add a movie folder and press Scan Library, or change your filters.</p><button class="primary" id="emptyAdd">+ Add movie folder</button></div>';
$('movieGrid').querySelectorAll('[data-movie]').forEach(el=>{el.onclick=()=>safe(()=>showMovie(+el.dataset.movie));el.onkeydown=e=>{if(e.target===el&&(e.key==='Enter'||e.key===' ')){e.preventDefault();el.click();}};});
$('movieGrid').querySelectorAll('[data-copy-title]').forEach(el=>el.onclick=e=>{e.preventDefault();e.stopPropagation();safe(async()=>{await copyText(el.dataset.copyTitle);toast('Movie name copied.');});});
if($('emptyAdd'))$('emptyAdd').onclick=addFolder;
}
function movieCard(m){let missing=m.status!=='available';let poster=m.poster_path?`<img loading="lazy" alt="Poster for ${esc(m.display_title)}" src="${artwork(m.id,m.poster_path)}" onerror="this.style.display='none';this.nextElementSibling?.classList.remove('hidden')"><div class="poster-none hidden"><span>◉</span><b>${esc(m.display_title)}</b></div>`:`<div class="poster-none"><span>◉</span><b>${esc(m.display_title)}</b></div>`;
const summary=m.sub_count?`${m.sub_count} subtitles · AR ${m.arabic_count} / EN ${m.english_count}`:'No subtitles';const sources=(m.subtitle_sources||'').split(',').filter(Boolean);
return `<div role="button" tabindex="0" class="movie-card ${missing?'dim':''}" data-movie="${m.id}" title="${esc(m.display_title)}"><div class="poster-frame">${poster}<div class="poster-badges"><span class="tag quality">${esc((m.resolution_tag||m.source||'MOVIE')+(m.resolution_tag&&!m.resolution_verified?'*':''))}</span>${missing?`<span class="tag ${m.status}">${esc(m.status.toUpperCase())}</span>`:''}</div></div><div class="movie-title-row"><div class="movie-title" title="${esc(m.display_title)}">${esc(m.display_title)}</div><button type="button" class="copy-title" data-copy-title="${esc(m.display_title)}" title="Copy the movie name" aria-label="Copy the movie name">⧉</button></div><div class="movie-sub"><span>${esc(m.year||'Year unknown')}</span><span>${m.imdb_rating!=null?`★ ${Number(m.imdb_rating).toFixed(1)}`:esc(m.release_group||'')}</span></div><div class="movie-genres" title="${esc(m.genres||'Genre unknown')}">${esc(m.genres||'Genre unknown')}</div><div class="movie-subs" title="${esc(summary)}">◉ ${esc(summary)}</div>${sources.length?`<div class="movie-source-tags">${sources.slice(0,2).map(x=>`<span>${esc(x)}</span>`).join('')}${sources.length>2?`<span>+${sources.length-2}</span>`:''}</div>`:''}</div>`;}
function setView(v){state.view=v;state.page=1;state.filter=v==='archived'?'missing':v==='posters'?'poster_missing':'all';state.group='';document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('settingsView').classList.toggle('hidden',v!=='settings');$('catalogView').classList.toggle('hidden',v==='settings');document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x.dataset.filter===state.filter));$('filters').classList.toggle('hidden',v==='posters');$('groupRow').classList.toggle('hidden',v!=='collections');let titles={home:['Your Movie Library',"A beautiful overview of every movie you’ve collected."],library:['All Movies','Browse, search, and manage your local collection.'],archived:['Missing & Archived Movies','Original filenames remain searchable even after the files disappear.'],collections:['Release Group Collections','Organize titles by encoding/release team.'],posters:['Movies Awaiting Posters','Add local artwork or search for reusable artwork online.']};if(titles[v]){$('catalogTitle').textContent=titles[v][0];$('catalogDesc').textContent=titles[v][1]};if(v==='collections')safe(loadGroups);if(v!=='settings')safe(refreshMovies);else safe(refreshBase);}
async function loadGroups(){const d=await api('/api/groups');state.groups=d.items;$('groupRow').innerHTML=`<button data-group="">All groups</button>`+d.items.map(g=>`<button data-group="${esc(g.group)}">${esc(g.group)} (${g.count})</button>`).join('');$('groupRow').querySelectorAll('button').forEach(el=>el.onclick=()=>{state.group=el.dataset.group;state.page=1;safe(refreshMovies);});}
function addFolder(){openModal(`<h2>Add Movie Folder</h2><p>MovieVault reads files without changing their names or deleting media. Posters are copied into the cache by default.</p><div class="field"><label>Folder path</label><div class="formrow"><input id="newRoot" placeholder="D:\Movies"><button class="secondary" id="pickRoot">Browse</button></div></div><div class="dialog-actions"><button class="primary" id="saveRoot">Add Folder & Scan</button><button class="secondary" id="cancelRoot">Cancel</button></div>`);$('cancelRoot').onclick=closeModal;$('pickRoot').onclick=()=>pickPath('folder','newRoot');$('saveRoot').onclick=()=>safe(async()=>{let path=$('newRoot').value.trim();if(!path)throw Error('Choose a folder first.');let r=await api('/api/roots','POST',{path});closeModal();toast('Folder added: '+r.path);await refreshBase();await startScan([r.id]);});}
async function pickPath(type,target){let fn=window.pywebview?.api?.[type==='folder'?'pick_folder':type==='imdb'?'pick_imdb':'pick_backup'];if(fn){let picked=await fn();if(picked)$(target).value=picked;}else toast('Native Browse is available in the packaged desktop app. You can paste the full path here.');}
async function startScan(rootIds){const data=await api('/api/scan','POST',rootIds?{root_ids:rootIds}:{});toast('Scanning files in the background…');watchJob(data.job_id);}
function watchJob(id){if(state.job===id)return;state.job=id;$('cancelActiveJob').classList.remove('hidden');const poll=async()=>{try{let j=await api(`/api/jobs/${id}`);$('footerState').textContent=j.state==='running'?`${j.type}: ${j.done}/${j.total} · ${j.message}`:j.message;
if(j.state==='running'){setTimeout(poll,1000);}else{state.job=null;$('cancelActiveJob').classList.add('hidden');toast(j.state==='completed'?`Completed: ${j.message}`:`Operation failed: ${j.message}`,j.state!=='completed');await refreshBase();if(state.view!=='settings')await refreshMovies();if(j.type==='poster'&&state.movie)await showMovie(state.movie.id);}}
catch(e){state.job=null;$('cancelActiveJob').classList.add('hidden');toast(e.message,true)}};poll();}
function dl(k,v){return `<div class="detail-line"><span>${esc(k)}</span><b>${esc(v??'—')}</b></div>`}
function showBadge(s){return `<span class="pill ${s==='available'?'ok':'bad'}">● ${esc(s.toUpperCase())}</span>`}
async function showMovie(id){let m=await api(`/api/movies/${id}`);state.movie=m;const cover=m.poster_path?`<img src="${artwork(id,m.poster_path)}" alt="${esc(m.display_title)}">`:`<div class="poster-none"><span>◉</span><b>No poster available</b></div>`;
const bits=[m.resolution_tag,m.source,m.hdr?'HDR':'',m.release_group].filter(Boolean).map(s=>`<span class="pill">${esc(s)}</span>`).join('');
openModal(`<div class="movie-detail"><div><div class="detail-poster">${cover}</div><div class="dialog-actions"><button class="secondary" id="replacePoster">▧ Change Poster</button><button class="secondary" id="framePoster" ${m.poster_locked?'disabled title="Unlock the current poster first"':''}>▧ Generate Custom Poster</button><button class="secondary" id="getPoster" ${m.poster_locked?'disabled title="Unlock the poster under Edit Metadata first"':''}>⟳ ${m.poster_path?'Refresh Poster Online':'Find Poster Online'}</button></div><div class="help">Poster: ${esc(m.poster_source||'not assigned')} ${m.poster_locked?'🔒 Locked':''}</div>${m.poster_credit?`<div class="help">${esc(m.poster_credit)}</div>`:''}</div>
<div><h2 class="detail-title">${esc(m.display_title)} ${m.year?'('+esc(m.year)+')':''}</h2><div class="pills">${showBadge(m.status)}${bits}${m.watched?'<span class="pill ok">✓ Watched</span>':''}${m.imdb_rating!=null?`<span class="pill">★ IMDb ${Number(m.imdb_rating).toFixed(1)}</span>`:''}${m.tmdb_rating!=null?`<span class="pill">TMDb ${Number(m.tmdb_rating).toFixed(1)}</span>`:''}</div><div class="quiet">${esc(m.genres||'Genre not matched yet')}${m.imdb_id?` · <a href="https://www.imdb.com/title/${esc(m.imdb_id)}/" target="_blank" rel="noopener">IMDb ↗</a>`:''}</div>
<div class="detail-actions"><button class="primary" id="playMovie" ${m.status!=='available'?'disabled':''}>▶ Play Movie</button><button class="secondary" id="openFolder" ${m.status!=='available'?'disabled':''}>▣ Open Folder</button><button class="secondary" id="editMovie">✎ Edit Metadata</button><button class="secondary" id="matchImdb">♧ Match IMDb</button><button class="secondary" id="refreshDetails">⟳ Refresh Movie & Cast</button><button class="secondary" id="askGemini">✦ AI Fix Unmatched Title</button><button class="icon-action" id="copyDisplay" title="Copy the movie name">⧉ Copy Name</button></div>
<div class="panel-head"><h3>Movie Details</h3><span class="quiet">The essential details only</span></div><div class="detail-summary">${dl('Genre',m.genres||'Unknown')}${dl('Year',m.year||'Unknown')}${dl('File Size',size(m.size_bytes))}${dl('Resolution',m.resolution||m.resolution_tag||'Unknown')}${dl('Video Bitrate',bit(m.video_bitrate)+(m.video_bitrate_estimated?' (estimate)':''))}${dl('Audio Codec',m.audio_codec||'Unknown')}${dl('Audio Bitrate',bit(m.audio_bitrate))}${dl('Overall Bitrate',bit(m.overall_bitrate)+(m.overall_bitrate_estimated?' (estimate)':''))}${dl('Audio Channels',m.audio_layout||m.channels||'Unknown')}${dl('Subtitle Format',m.subtitles.length?[...new Set(m.subtitles.map(s=>s.format))].join(', '):'No subtitles detected')}${dl('Source',m.source||'Unknown')}${dl('Release Group',m.release_group||'Unknown')}</div>
<div class="detail-extra"><section class="panel"><div class="panel-head"><h3>Tech. Media Info</h3><button class="icon-action" id="fullInfo">View Full Info</button></div><div class="info-grid">${dl('Size',size(m.size_bytes))}${dl('Video',m.video_codec||'N/A')}${dl('Video Rate',bit(m.video_bitrate))}${dl('Audio',m.audio_codec||'N/A')}${dl('Audio Rate',bit(m.audio_bitrate))}${dl('Total Rate',bit(m.overall_bitrate))}</div></section><section class="panel"><h3>Movie Identity</h3><div class="quiet">First detected filename (immutable)</div><div class="filewrap">${esc(m.original_filename)}</div><div class="quiet" style="margin-top:9px">Current filename</div><div class="filewrap">${esc(m.current_filename)}</div><button class="icon-action" style="margin-top:8px" id="copyOriginal">Copy Original Name</button></section></div>
<div class="detail-extra"><section class="panel"><h3>Subtitle Management</h3><div class="quiet">Default source: ${esc(m.subtitle_source||'Unknown')} · Quality: ${esc(m.translation_quality||'Unrated')}</div><div class="subtable-scroll">${m.subtitles.length?`<table class="sub-list"><thead><tr><th>Subtitle Filename (hover for full path)</th><th>Format</th><th>Language</th><th>Source</th><th>Translator</th><th>Quality</th><th></th></tr></thead><tbody>${m.subtitles.map(s=>`<tr><td><span class="subtitle-filename" title="${esc(s.path||s.filename)}">${esc(s.filename)}</span><small>${esc(s.kind)}</small></td><td>${esc(s.format)}</td><td><select data-sub-key="language">${langOptions(s.language)}</select></td><td><select data-sub-key="source">${sourceOptions(s.source)}</select></td><td><input type="text" maxlength="100" data-sub-key="translator" value="${esc(s.translator||'')}" placeholder="Optional"></td><td><select data-sub-key="quality">${qualityOptions(s.quality)}</select></td><td><button class="secondary" data-apply-sub="${s.id}">Apply Changes</button></td></tr>`).join('')}</tbody></table>`:'<p class="quiet">No external or embedded subtitles detected.</p>'}</div><div class="field"><label>Preferred playback subtitle</label><select id="preferredPlayback"><option value="auto" ${m.playback_preference==='auto'?'selected':''}>Auto-select if possible</option><option value="ask" ${m.playback_preference==='ask'?'selected':''}>Ask me every time</option><option value="none" ${m.playback_preference==='none'?'selected':''}>Play without subtitle</option>${m.subtitles.filter(s=>s.kind==='external').map(s=>`<option value="sub-${s.id}" ${(m.playback_preference==='selected'&&m.preferred_subtitle_id===s.id)?'selected':''}>${esc(s.language)} — ${esc(s.source)} (${esc(s.filename)})</option>`).join('')}</select><button class="secondary" id="savePreferredSubtitle">Save Preferred Subtitle</button></div></section><section class="panel"><h3>History & Status</h3>${dl('First added',m.added_at)}${dl('Last seen',m.last_seen)}${dl('Location',m.root_path)}${dl('Probe',m.probe_error||'OK')}${dl('Poster locked',m.poster_locked?'Yes':'No')}${m.overview?`<p>${esc(m.overview)}</p>`:''}${m.ai_suggestion?`<div class="help">AI suggestion: ${esc(m.ai_suggestion.suggested_title)} (${esc(m.ai_suggestion.suggested_year||'?')}) · ${esc(m.ai_suggestion.status)}</div>`:''}<h3>Cast</h3><div class="cast-people">${(m.cast_names||'').split(',').filter(Boolean).map(x=>`<span>${esc(x.trim())}</span>`).join('')||'<span>Cast not retrieved yet</span>'}</div></section></div></div></div>`, 'large');
$('playMovie').onclick=()=>{const external=m.subtitles.filter(s=>s.kind==='external');if(m.playback_preference==='ask'||(m.playback_preference==='auto'&&external.length>1))showPlaybackChoice(m);else safe(()=>launchChosenMovie(m));};$('openFolder').onclick=()=>safe(()=>api(`/api/movies/${id}/folder`,'POST',{}));$('editMovie').onclick=()=>editMovie(m);$('fullInfo').onclick=()=>fullInfo(m);$('copyOriginal').onclick=()=>{copyText(m.original_filename);toast('Original filename copied.');};$('askGemini').onclick=()=>safe(async()=>{if(!confirm('Send this film title/year (not the video) to your Gemini API for a suggestion, then verify it through TMDB? This may consume API quota.'))return;const r=await api(`/api/movies/${id}/ai/resolve`,'POST',{});toast('AI title suggestion and independent verification started.');watchJob(r.job_id);});
$('copyDisplay').onclick=()=>safe(async()=>{await copyText(m.display_title);toast('Movie name copied.');});$('refreshDetails').onclick=()=>safe(async()=>{const d=await api(`/api/movies/${id}/details/refresh`,'POST',{});toast('TMDb cast and metadata refresh started.');watchJob(d.job_id);});$('matchImdb').onclick=()=>safe(async()=>{let x=await api(`/api/movies/${id}/match`,'POST',{});toast(x.matched?'IMDb metadata matched.':'No unique exact IMDb match for this title and year.');await showMovie(id);});$('replacePoster').onclick=()=>{$('posterInput').value='';$('posterInput').dataset.id=id;$('posterInput').click();};$('framePoster').onclick=()=>safe(async()=>{if(!confirm('Create a custom poster from a movie frame? It will be labelled as non-official artwork. The video file stays unchanged.'))return;const d=await api(`/api/movies/${id}/poster/generate`,'POST',{});toast('Generating a custom frame poster…');watchJob(d.job_id);});$('getPoster').onclick=()=>safe(async()=>{let d=await api(`/api/movies/${id}/poster/fetch`,'POST',{replace:!!m.poster_path});toast('Searching '+(state.config.poster_provider==='tmdb'?'TMDB':'Wikimedia Commons')+' for matching artwork…');watchJob(d.job_id);});
$('modalContent').querySelectorAll('[data-apply-sub]').forEach(btn=>btn.onclick=()=>safe(async()=>{const row=btn.closest('tr');const values={};row.querySelectorAll('[data-sub-key]').forEach(el=>values[el.dataset.subKey]=el.value);await api(`/api/subtitles/${btn.dataset.applySub}`,'PATCH',values);toast('Subtitle changes permanently saved.');await showMovie(id);}));
$('savePreferredSubtitle').onclick=()=>safe(async()=>{const v=$('preferredPlayback').value;await api(`/api/movies/${id}`,'PATCH',{playback_preference:v.startsWith('sub-')?'selected':v,preferred_subtitle_id:v.startsWith('sub-')?Number(v.slice(4)):null});toast('Playback preference updated. You can change it whenever you like.');await showMovie(id);});} 
async function launchChosenMovie(m,subtitleId=null,none=false){const result=await api(`/api/movies/${m.id}/play`,'POST',{subtitle_id:subtitleId,no_subtitles:none});toast(`Started playback with ${result.player}. Original subtitles were not renamed.`);state.modalBackMovieId=null;await showMovie(m.id);}
function showPlaybackChoice(m){state.modalBackMovieId=m.id;const subs=m.subtitles.filter(s=>s.kind==='external');
openModal(`<h2>Select Subtitle for Playback</h2><p>The original movie and subtitle filenames are NEVER modified. A compatible player (VLC or mpv) is used to pass a chosen subtitle directly.</p><div class="field"><label>Subtitle for this session</label><select id="playSelect"><option value="none">No subtitles</option>${subs.map(s=>`<option value="${s.id}">${esc(s.language)} — ${esc(s.source||'Unknown')} · ${esc(s.filename)}</option>`).join('')}</select></div><div class="dialog-actions"><button class="primary" id="launchPlay">▶ Play with Selection</button><button class="secondary" id="cancelPlay">Back to Movie</button></div>`);
$('cancelPlay').onclick=()=>{state.modalBackMovieId=null;showMovie(m.id)};
$('launchPlay').onclick=()=>safe(async()=>{const v=$('playSelect').value;await launchChosenMovie(m,v==='none'?null:Number(v),v==='none');});}
function sourceOptions(v){const names=[...new Set([...state.subtitleSources,v].filter(Boolean))];return names.map(s=>`<option value="${esc(s)}" ${v===s?'selected':''}>${esc(s)}</option>`).join('')}
function langOptions(v){return [...new Set(['Arabic','English','French','Spanish','German','Italian','Unknown','Other',v].filter(Boolean))].map(x=>`<option value="${esc(x)}" ${x===v?'selected':''}>${esc(x)}</option>`).join('')}
function qualityOptions(v){return ['Unrated','Excellent','Good','Average','Poor','Out of Sync'].map(s=>`<option ${v===s?'selected':''}>${esc(s)}</option>`).join('')}
function editMovie(m){state.modalBackMovieId=m.id;openModal(`<h2>Edit Movie Metadata</h2><p>Manual edits are locked against automatic rescan changes. The original filename is always preserved.</p><div class="field"><label>Display Title</label><input id="editTitle" value="${esc(m.display_title)}"></div><div class="formrow"><div class="field" style="flex:1"><label>Production Year</label><input id="editYear" type="number" min="1870" max="2100" value="${esc(m.year||'')}"></div><div class="field" style="flex:2"><label>Genre(s)</label><input id="editGenre" value="${esc(m.genres)}" placeholder="Action, Drama"></div></div><div class="formrow"><div class="field" style="flex:1"><label>Release / Encoding Group</label><input id="editGroup" value="${esc(m.release_group)}"></div><div class="field" style="flex:1"><label>Source</label><input id="editSource" value="${esc(m.source)}"></div></div><div class="field"><label>IMDb ID or URL</label><input id="editImdb" value="${esc(m.imdb_id)}" placeholder="tt0468569"></div><div class="formrow"><div class="field" style="flex:1"><label>Subtitle Source (default)</label><select id="editSubSource">${sourceOptions(m.subtitle_source)}</select></div><div class="field" style="flex:1"><label>Translation Quality (default)</label><select id="editQuality">${qualityOptions(m.translation_quality)}</select></div></div><div class="field"><label>Personal Notes</label><textarea id="editNotes">${esc(m.notes)}</textarea></div><label class="switchrow"><b>Watched</b><input type="checkbox" id="editWatched" ${m.watched?'checked':''}></label><label class="switchrow"><b>Add to Favorites</b><input type="checkbox" id="editFavorite" ${m.favorite?'checked':''}></label><div class="field"><label>Your personal rating (0–10, optional; IMDb rating remains separate)</label><input id="editPersonalRating" type="number" min="0" max="10" step="0.1" value="${m.personal_rating??''}"></div><label class="switchrow"><b>Lock current poster</b><input type="checkbox" id="editPosterLock" ${m.poster_locked?'checked':''}></label><div class="dialog-actions"><button class="primary" id="saveMovie">Save Changes</button><button class="secondary" id="cancelEdit">Cancel</button></div>`,'medium');$('cancelEdit').onclick=()=>{state.modalBackMovieId=null;showMovie(m.id)};$('saveMovie').onclick=()=>safe(async()=>{let fields={display_title:$('editTitle').value,year:$('editYear').value||null,genres:$('editGenre').value,release_group:$('editGroup').value,source:$('editSource').value,imdb_id:$('editImdb').value,subtitle_source:$('editSubSource').value,translation_quality:$('editQuality').value,notes:$('editNotes').value,watched:$('editWatched').checked,favorite:$('editFavorite').checked,personal_rating:$('editPersonalRating').value||null,poster_locked:$('editPosterLock').checked};await api(`/api/movies/${m.id}`,'PATCH',fields);toast('Manual changes safely saved.');state.modalBackMovieId=null;await showMovie(m.id);await refreshMovies();});}
function fullInfo(m){let raw=JSON.stringify(JSON.parse(m.raw_probe||'{}'),null,2);openModal(`<h2>Full Technical Media Information</h2><p>All data returned by ffprobe, including every video, audio and subtitle stream. No artificial bitrate values are inserted.</p><div class="dialog-actions"><button class="secondary" id="copyFull">Copy JSON</button><button class="secondary" id="backDetails">← Movie Details</button></div><pre class="long-info" id="rawProbe">${esc(raw)}</pre>`,'medium');$('copyFull').onclick=()=>{copyText(raw);toast('Full media information copied.');};$('backDetails').onclick=()=>showMovie(m.id);}
async function copyText(t){try{await navigator.clipboard.writeText(t)}catch{const a=document.createElement('textarea');a.value=t;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}}
$('posterInput').onchange=()=>safe(async()=>{let file=$('posterInput').files[0],id=Number($('posterInput').dataset.id);if(!file)return;if(file.size>12_000_000)throw Error('Image exceeds 12 MB.');await api(`/api/movies/${id}/poster/upload`,'POST',file);toast('Poster saved in library cache and locked as a manual selection.');await showMovie(id);await refreshMovies();});
// Setup and listeners
for(const btn of document.querySelectorAll('.nav'))btn.onclick=()=>setView(btn.dataset.view);
for(const btn of document.querySelectorAll('[data-filter]'))btn.onclick=()=>{state.filter=btn.dataset.filter;state.page=1;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===btn));safe(refreshMovies);};
$('search').addEventListener('input',e=>{state.q=e.target.value;state.group='';state.page=1;clearTimeout(window.searchTimer);window.searchTimer=setTimeout(()=>safe(refreshMovies),240)});$('sort').onchange=e=>{state.sort=e.target.value;state.page=1;safe(refreshMovies)};$('prevBtn').onclick=()=>{state.page=Math.max(1,state.page-1);safe(refreshMovies)};$('nextBtn').onclick=()=>{state.page++;safe(refreshMovies)};
function smartUpdateDialog(){openModal(`<h2>Smart Library Update</h2><p>Choose what to update. Manual edits, first-seen filenames, and offline archives are preserved. Online metadata/artwork may use provider quotas.</p><div class="field"><label>Update mode</label><select id="updateMode"><option value="quick">Quick Scan — changed movies and subtitle files</option><option value="metadata">Refresh Local IMDb Ratings + TMDb Cast & Details</option><option value="posters">Missing Posters Only</option><option value="full">Full Update — Scan, Metadata and Posters</option></select></div><div class="field"><label>Maximum network items in one run (safe batch)</label><input type="number" id="updateLimit" value="50" min="1" max="250"></div><label class="switchrow"><b>Allow Gemini suggestions for unmatched titles</b><input type="checkbox" id="useAiForUpdate"></label><div class="dialog-actions"><button id="runUpdate" class="primary">Start Smart Update</button><button id="cancelUpdate" class="secondary">Cancel</button></div>`);
$('cancelUpdate').onclick=closeModal;$('runUpdate').onclick=()=>safe(async()=>{const mode=$('updateMode').value;const limit=Number($('updateLimit').value);const include=$('useAiForUpdate').checked;const r=await api('/api/update-all','POST',{mode,limit,include_gemini:include});closeModal();toast('Smart update started in background.');watchJob(r.job_id);});}
$('updateAllBtn').onclick=smartUpdateDialog;
$('cancelActiveJob').onclick=()=>safe(async()=>{if(!state.job)return;await api('/api/jobs/'+state.job+'/cancel','POST',{});toast('Cancellation requested. The current safe step will finish first.');});
$('scanBtn').onclick=()=>safe(()=>startScan());$('addBtn').onclick=addFolder;$('settingsAdd').onclick=addFolder;$('backupBtn').onclick=$('createBackup').onclick=()=>safe(async()=>{let r=await api('/api/backup','POST',{});toast('Backup saved to '+r.path);});
for(const el of document.querySelectorAll('[data-setting]'))el.onchange=()=>safe(async()=>{let obj={[el.dataset.setting]:el.checked?'1':'0'};await api('/api/settings','POST',obj);toast('Setting saved.');});
$('findMorePosters').onclick=()=>safe(async()=>{let d=await api('/api/posters/batch','POST',{limit:10});toast('Artwork search queued.');watchJob(d.job_id);});
$('connectTmdb').onclick=()=>safe(async()=>{const token=$('tmdbReadToken').value.trim();if(!token)throw Error('Paste the API Read Access Token into this field first.');$('connectTmdb').disabled=true;$('tmdbStatus').textContent='Testing connection with TMDB…';try{await api('/api/tmdb/connect','POST',{read_token:token});$('tmdbReadToken').value='';toast('TMDB connected securely. Prior missing posters can be retried.');await refreshBase();}finally{$('connectTmdb').disabled=false;}});
$('disconnectTmdb').onclick=()=>safe(async()=>{if(!confirm('Disconnect TMDB? Locally protected token will be removed; existing manually chosen posters will remain.'))return;await api('/api/tmdb/disconnect','POST',{});$('tmdbReadToken').value='';toast('TMDB disconnected.');await refreshBase();});
$('posterProvider').onchange=()=>safe(async()=>{try{await api('/api/settings','POST',{poster_provider:$('posterProvider').value});toast('Artwork provider updated.');}finally{await refreshBase();}});

$('downloadImdbRatings').onclick=()=>safe(async()=>{if(!confirm('Download the official IMDb ratings dataset and update linked film ratings? This requires internet, no API key.'))return;const d=await api('/api/imdb/ratings/download','POST',{});watchJob(d.job_id);});
$('downloadImdb').onclick=()=>safe(async()=>{if(!confirm('Download the official IMDb non-commercial title dataset? This is a large one-time download and its usage terms apply.'))return;let d=await api('/api/imdb/download','POST',{});toast('IMDb download and local indexing started.');watchJob(d.job_id);});
$('imdbChoose').onclick=()=>pickPath('imdb','imdbPath');$('importImdb').onclick=()=>safe(async()=>{let path=$('imdbPath').value.trim();if(!path)throw Error('Select title.basics.tsv.gz first.');let d=await api('/api/imdb/import','POST',{path});toast('IMDb dataset import started. It may be large.');watchJob(d.job_id);});
// Safe, preview-first legacy import. Only snapshots are staged; nothing in v1 is modified.
$('openMigration').onclick=()=>{setView('settings');$('migrationPanel').scrollIntoView({behavior:'smooth',block:'center'});};
$('legacyChoose').onclick=()=>pickPath('folder','legacyPath');
$('legacyChooseZip').onclick=()=>pickPath('backup','legacyPath');
$('legacyPath').addEventListener('input',()=>{migrationPreview=null;$('legacyImport').disabled=true;$('legacySummary').textContent='Select Preview Data to verify the source and item counts.';});
function showLegacy(d){if(d.found===false){migrationPreview=null;$('legacyImport').disabled=true;$('legacySummary').textContent=d.hint;return;}
migrationPreview=d;$('legacyPath').value=d.source||'';$('legacyImport').disabled=false;
$('legacySummary').textContent=`${d.notice?d.notice+'\n':''}Validated ${d.kind}: ${Number(d.movies).toLocaleString()} movies · ${Number(d.subtitles).toLocaleString()} subtitles · ${Number(d.imdb_titles).toLocaleString()} IMDb titles · ${d.roots} watched folders · ${d.posters} poster files. Legacy schema ${d.schema}. No credentials will be imported.`;}
async function loadSubtitleSources(){const d=await api('/api/subtitle-sources');state.subtitleSources=d.items;
$('fSubtitleSource').innerHTML='<option value="">Any subtitle source</option>'+d.items.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');
$('customSubtitleSources').textContent=d.items.slice(7).join(' · ')||'Add your first custom source.';}
$('connectGemini').onclick=()=>safe(async()=>{const key=$('geminiKey').value.trim();if(!key)throw Error('Paste your Gemini API key first.');const d=await api('/api/gemini/connect','POST',{api_key:key});$('geminiKey').value='';$('geminiModel').value=d.model;toast('Gemini API connected. Suggestions require independent TMDb verification.');await refreshBase();});
$('disconnectGemini').onclick=()=>safe(async()=>{if(!confirm('Remove the locally protected Gemini API key?'))return;await api('/api/gemini/disconnect','POST',{});$('geminiKey').value='';await refreshBase();toast('Gemini disconnected.');});
$('diagnosticExport').onclick=()=>safe(async()=>{let r=await api('/api/diagnostics/export','POST',{});toast('Diagnostic ZIP saved. Review it before sharing: '+r.path);});
$('addSubtitleSource').onclick=()=>safe(async()=>{const name=$('newSubtitleSource').value.trim();if(!name)throw Error('Enter a subtitle provider/translator name.');await api('/api/subtitle-sources','POST',{name});$('newSubtitleSource').value='';await loadSubtitleSources();toast('Custom source added.');});
$('defaultSubLang').onchange=()=>safe(async()=>{await api('/api/settings','POST',{default_external_subtitle_lang:$('defaultSubLang').value});toast('Default subtitle language saved.');});
$('themeChoice').onchange=()=>safe(async()=>{await api('/api/settings','POST',{theme:$('themeChoice').value});document.documentElement.dataset.theme=$('themeChoice').value;toast('Theme saved.');});
for(const id of ['fGenre','fActor','fSubtitleLanguage','fSubtitleSource','fTranslator','fYearFrom','fYearTo','fFavorite']){let el=$(id);el.addEventListener(['fGenre','fActor','fTranslator','fYearFrom','fYearTo'].includes(id)?'input':'change',()=>{state.page=1;clearTimeout(window.filterTimer);window.filterTimer=setTimeout(()=>safe(refreshMovies),200);});}
$('clearAdvancedFilters').onclick=()=>{for(const id of ['fGenre','fActor','fSubtitleLanguage','fSubtitleSource','fTranslator','fYearFrom','fYearTo','fFavorite'])$(id).value='';state.page=1;safe(refreshMovies);};
$('legacyDetect').onclick=()=>safe(async()=>showLegacy(await api('/api/migration/detect')));
$('legacyPreview').onclick=()=>safe(async()=>showLegacy(await api('/api/migration/preview','POST',{path:$('legacyPath').value.trim()})));
$('legacyImport').onclick=()=>safe(async()=>{if(!migrationPreview)throw Error('Preview the previous library first.');
const p=$('legacyPath').value.trim();if(p!==migrationPreview.source)throw Error('The source path changed. Preview it again first.');
if(!confirm(`Stage the previous MovieVault library?\n${migrationPreview.movies} movies and ${migrationPreview.imdb_titles} IMDb titles.\nExisting v1 files will NEVER be modified. Restart required.`))return;
const r=await api('/api/migration/stage','POST',{path:p});$('legacyImport').disabled=true;
$('legacySummary').textContent=`Import staged safely: ${r.counts.movies} movies, ${r.counts.imdb_titles} IMDb titles. Close and restart MovieVault to activate.`;toast('Previous library snapshot staged. Restart MovieVault to activate.');});
$('restoreChoose').onclick=()=>pickPath('backup','restorePath');$('restoreBtn').onclick=()=>safe(async()=>{let path=$('restorePath').value.trim();if(!path)throw Error('Select an existing backup ZIP.');if(!confirm('Stage a full restoration? Your current catalog will first get a safety backup on next launch. Restart MovieVault to complete.'))return;let d=await api('/api/restore','POST',{path});toast(d.message);});
$('rootSettings').onclick=e=>{let el=e.target.closest('[data-remove-root]');if(!el)return;safe(async()=>{if(!confirm('Stop watching this folder? Catalog items will be kept as Offline, never deleted.'))return;await api('/api/roots/'+el.dataset.removeRoot,'DELETE',{});await refreshBase();toast('Stopped watching folder; movie records retained.');});};
async function boot(){await loadSubtitleSources();await refreshBase();await refreshMovies();}
boot().catch(e=>toast(e.message,true));
